<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHdqR40Q\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHdqR40Q/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHdqR40Q.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHdqR40Q\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerHdqR40Q\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'HdqR40Q',
    'container.build_id' => '1a227f02',
    'container.build_time' => 1636475588,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHdqR40Q');
